#!/usr/bin/env bash
# This script reads and displays the content of /etc/passwd

while IFS=':' read -r username _ uid _ _ home _; do
  echo "Username: $username"
  echo "User ID: $uid"
  echo "Home Directory: $home"
  echo
done < /etc/passwd

