#!/usr/bin/env bash
#manage 
if [[ "$#" == "1" ]]; then
  if [[ "$1" == "start" ]]; then
# Bash script manages manage_my_process
start() {
    ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process started"
  elif [[ "$1" == "stop" ]]; then
    if test -f "/var/run/my_process.pid"; then
      kill "$(cat /var/run/my_process.pid)"
    fi
    rm /var/run/my_process.pid
}
stop() {
    sudo rm -f /var/run/my_process.pid &
    sudo pkill -f manage_my_process &
    echo "manage_my_process stopped"
  elif [[ "$1" == "restart" ]]; then
    # stop program
    if test -f "/var/run/my_process.pid"; then
      kill "$(cat /var/run/my_process.pid)"
    fi
    # start program
}
restart() {
    sudo pkill manage_my_process &
    rm /var/run/my_process.pid &
    ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process restarted"
  else
}
if [ $# -lt 1 ] || [ $# -ge 2 ]; then
    echo "Usage: manage_my_process {start|stop|restart}"
  fi
else
  echo "Usage: manage_my_process {start|stop|restart}"
    case $1 in
	"start")
	    start
	    ;;
	"stop")
	    stop
	    ;;
	"restart")
	    restart
	    ;;
    esac
fi
