#!/usr/bin/env bash
# This script  displays:To infinity and beyond indefinitely, With a sleep 2 in between each iteration
trap 'echo I am invincible!!!; exit 0' SIGTERM
while true; do
echo "To infinity and beyond"
sleep 2
done
